<a href="https://colab.research.google.com/github/Henry-0810/Artificial-Intelligence/blob/main/AI_Stuff.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module Content
1. 30% Genetic Algorithm
2. 30% Search Tree Algorithm
3. 40% Data Driven project - 2 datasets

# Lecture 1
Genetic Algorithm Start

In [ ]:
import numpy as np
from copy import deepcopy

x = [1, 2, 5, -4, 6, 8]
y = [2, 2, 2, 2, 2, 2]
z = [-1, -2, -5, 4, -6, -8]


In [ ]:
def sphere(x):
  total = 0
  for i in x:
    total += i*i
  return total

In [ ]:
sphere(x)

146

In [ ]:
sphere(z)

146

In [ ]:
class problem:
  def __init__(self):
    self.number_of_genes = 8
    self.min_value = -10
    self.max_value = 10
    self.cost_function = sphere
    pass

In [ ]:
class individual:
  def __init__(self, problem):
    self.chromosome = np.random.uniform(problem.min_value, problem.max_value, problem.number_of_genes)
    self.cost = problem.cost_function(self.chromosome)

  def mutate(self, rate_of_gene_mutation, range_of_gene_mutation):
    for index in range(len(self.chromosome)):
      if np.random.uniform() < rate_of_gene_mutation:
        self.chromosome[index] += np.random.rand() * range_of_gene_mutation

  def crossover(self, parent2, explore_crossover):
    alpha = np.random.uniform(-explore_crossover, 1 + explore_crossover)
    child1 = deepcopy(self)
    child2 = deepcopy(parent2)
    child1.chromosome = alpha*self.chromosome + (1-alpha)*parent2.chromosome
    child2.chromosome = alpha*parent2.chromosome + (1-alpha)*self.chromosome
    return child1, child2


In [ ]:
def choose_indices_from(number_in_list):
  index_1 = np.random.randint(number_in_list)
  index_2 = np.random.randint(number_in_list)
  if index_1 == index_2:
    return choose_indices_from(number_in_list)
  return index_1,index_2

In [ ]:
p1 = problem()
par1 = parameters()

In [ ]:
p = problem()
p.number_of_genes

8

In [ ]:
test = individual(p)
test.chromosome

array([ 2.83976621,  7.09866697,  8.89162982, -1.7221497 ,  4.00141534,
        3.24444533, -8.76802892,  0.75020067])

In [ ]:
test.cost

244.46110776046694

In [ ]:
population = []
for i in range(1000):
  population.append(individual(p))

In [ ]:
population[0:5]

In [ ]:
test.mutate(0.5, 2)

In [ ]:
test.chromosome

array([ 3.31877062,  8.73158259, 10.57323768, -1.7221497 ,  4.00141534,
        4.12777585, -8.76802892,  0.75020067])

In [ ]:
p_test = problem()

i1 = individual(p_test)
i2 = individual(p_test)

print(i1.chromosome)
print(i2.chromosome)

print("\n")

c1, c2 = i1.crossover(i2, 2)
print(c1.chromosome)
print(c2.chromosome)

[-1.10949838 -9.66790428 -9.74594415 -9.89047344 -3.62670272 -4.01228827
  2.1622621   1.50682492]
[-9.83526651 -9.64348144 -5.99911784  0.54211452 -1.58816552 -1.30656815
  8.54632161 -1.40771211]


[-10.90996142  -9.64047344  -5.53764613   1.82702709  -1.33709243
  -0.97332257   9.33260382  -1.76667628]
[ -0.03480347  -9.67091228 -10.20741586 -11.17538601  -3.87777581
  -4.34553385   1.37597989   1.86578909]


In [ ]:
class parameters:
  def __init__(self):
    self.population_size  = 1000

    self.max_generation = 1000

    self.crossover_explore_rate = 0.2
    self.gene_mutate_rate = 0.2
    self.gene_mutate_range = 1

    self.birthrate_per_generation = 1

In [ ]:
def choose_parents(population_size):
  index1 = np.random.randint(0, population_size)
  index2 = np.random.randint(0, population_size)
  if index1 == index2:
    return choose_parents(population_size)
  else:
    return index1, index2

In [ ]:
def run_genetic(problem, params):
  """
  1. Read Variables
  2. Create Population
  3. Training Loop
  start loop
    4. Create Children
    5. Sort Population
    6. Cull Population - choose parent, use it to find more children
    7. Check Solution
  end loop

  How to effectively choose parents (roulette, tournament)
  """
  # Cost Function
  cost_function = problem.cost_function
  acceptable_cost = problem.acceptable_cost

  # Params

  population_size  = params.population_size

  max_generation = params.max_generation

  explore_crossover = params.crossover_explore_rate
  gene_mutate_rate = params.gene_mutate_rate
  gene_mutate_range = params.gene_mutate_range

  birthrate_per_generation = params.birthrate_per_generation

  population = []

  #placeholder for best solution
  best_solution = individual(problem)
  best_solution.cost = np.infty

  # 1. Create our population
  for i in range(population_size):
    new_individual = individual(problem)
    population.append(new_individual)

    if new_individual.cost < best_solution.cost:
      best_solution = deepcopy(new_individual)

  # 3. Create a loop
  for i in range(max_generation):
    children = []
    while len(children) < birthrate_per_generation:
    # 4. Create Children
    # choose parents
      parent1_index, parent2_index = choose_parents(population_size)
      parent1 = population[parent1_index]
      parent2 = population[parent2_index]

      # crossover
      child1, child2 = parent1.crossover(parent2, explore_crossover)

      # mutate
      child1.mutate(gene_mutate_rate, gene_mutate_range)
      child2.mutate(gene_mutate_rate, gene_mutate_range)

      # evaluate cost
      child1.cost = cost_function(child1.chromosome)
      child2.cost = cost_function(child2.chromosome)

      # add children to children
      children.append(child1)
      children.append(child2)

      population.extend(children)

      # 5. Sort Population
      population.sort(key=lambda x: x.cost)

      # 6. Cull Population
      population = population[:population_size]
      print(population[0].cost)

      # 7. Check solution
      if population[0].cost < best_solution.cost:
        best_solution = deepcopy(population[0])
        print(best_solution.cost)

      if best_solution.cost < acceptable_cost:
        break

  return population, best_solution


## Exercise 1
**Exercise**  Adjust the function above to look for the solution (1,2,3,4,5)

*Hint:    If x = 3 then (x-3) = 0*

In [ ]:
# https://colab.research.google.com/drive/1MnspGdFTfZzr_-ARdj7mFC1hAOJyRexS
def seq_cost(x):
  total = 0
  for i in range(5):
    total += (x[i] - (i+1))**2
  return total


In [ ]:
seq_cost([1,2,3,4,5])

0

In [ ]:
class exercise1:
  def __init__(self):
    self.number_of_genes = 5
    self.min_value = 1
    self.max_value = 6
    self.cost_function = seq_cost
    self.acceptable_cost = 0

In [ ]:
p, solution1 = run_genetic(exercise1(), parameters())
solution1.chromosome, solution1.cost

1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006848907
1.3675338006

(array([1.84315201, 2.32365485, 3.15574266, 4.12015804, 4.45224596]),
 1.1543859983620561)

## Exercise 2
**Exercise** Adjust the function above to look for the solution (1,2,4,8,...,2^m)  where m could be any integer greater than 2

*Hint: If x = 3 then (x-3) = 0 and you may need to use a for loop*

In [ ]:
def sumPows2(v):
  targetValue = 1
  sum = 0
  for x in v:
    sum += (x - targetValue)**2
    targetValue *= 2
  return sum


In [ ]:
sumPows2([1,2,4,8])

0

In [ ]:
class exercise2:
  def __init__(self):
    self.number_of_genes = 4
    self.min_value = 1
    self.max_value = 2**(self.number_of_genes)
    self.cost_function = sumPows2
    self.acceptable_cost = 0

In [ ]:
e1 = exercise2()
e1.max_value

16

In [ ]:
p, solution2 = run_genetic(exercise2(), parameters())
solution2.chromosome, solution2.cost

4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.931516878112155
4.93151687

(array([1.92939667, 3.62360258, 3.6237193 , 8.89204488]), 4.4371947328564545)

## Exercise 3
**Exercise**   Write a cost function which would solve the following linear inequality problem

Minimise the following function $3x+4y+5z$ subject to the following conditions..
$x\ge0 , y\ge0 , z\ge0$

$x+y+z >10$         
$2y+4z > 25$


In [ ]:
def costLP(v):
  if v[0] + v[1] + v[2] <10:  #x+y+z <10
    return 10000000
  if 2*v[1] +4*v[2] <25:  # 2y+4z<25
    return 10000000
  return 3*v[0] +4*v[1]+5*v[2]  #3x+4y+5z

In [ ]:
class problemLP:
  def __init__(self):
    self.number_of_genes = 3 # x,y,z
    self.min_value = 0
    self.max_value = 10
    self.cost_function = costLP
    self.acceptable_cost = 0

In [ ]:
p, solution3 = run_genetic(problemLP(), parameters())
solution3.chromosome, solution3.cost

44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.43362023890418
44.4336202

(array([3.54065485, 0.81772068, 6.08212175]), 44.303456054219254)

## Exercise 4
**Exercise** If you wanted to find the solution which ***maximised*** a given function e.g. $f(x,y,z) = 5-2x^2 -7y^4 - 10 z^6$  how could you construct the cost function here.

In [ ]:
def costLP(v):
  return -5 + 2*v[0]**2 - 7*v[1]**4 - 10*v[2]**6

In [ ]:
class problemLP:
  def __init__(self):
    self.number_of_genes = 3 # x,y,z
    self.min_value = 0
    self.max_value = 10
    self.cost_function = costLP
    self.acceptable_cost = 0

In [ ]:
p, solution4 = run_genetic(problemLP(), parameters())
solution4.chromosome, solution4.cost

-9957347.19221964
-9957347.19221964
-9957347.19221964
-9957347.19221964
-9957347.19221964
-9957347.19221964
-9957347.19221964
-9957347.19221964
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661497
-13154741.791661

(array([ 8.59295205,  4.57248211, 11.6911102 ]), -25537838.548424054)

# Lecture 2
## Exercise 1
Why does this save memory? If we wished to use 0's and 1's how would these be stored?

Boolean can be packed into bits, a boolean requires only a single bit to represent its two possible states (True/False). Systems can pack multiple boolean values into a single byte, allowing efficient storage.

1s and 0s can be represented as integers or character. Each value might occupy a full byte, increasing the storage usage/memory usage.

If using 1s and 0s is essential, binary encoding could be a choice? Not sure about this

## Exercise 2
Use np.random.choice to create an array of size 1000 of True or False values

In [ ]:
import numpy as np

np.random.choice([True, False], 1000)

array([False,  True, False, False, False, False,  True, False, False,
       False,  True,  True, False,  True, False,  True, False, False,
        True,  True, False,  True,  True, False,  True, False,  True,
        True, False,  True,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True, False, False,  True, False,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False, False,  True, False, False, False,
       False, False,  True, False,  True,  True,  True,  True, False,
       False,  True, False,  True, False,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False,  True,  True, False, False, False,  True,  True,
        True, False,  True, False,  True, False,  True,  True, False,
        True, False,  True, False,  True,  True,  True, False, False,
       False,  True,  True,  True, False,  True, False,  True,  True,
        True, False,


**Exercise 3**  Incorporate into the problem and individual class shells' below

In [ ]:
def cost():
  pass

class problem:
  def __init__(self):
    self.number_of_genes = 1000
    self.cost_function = None

class individual:
  # This class defines the individual for the genetic algorithm. We hope to find the individual which solves our problem
  chromosome = None

  def __init__(self, prob):    #  This is the constructor for the individual and as such needs the problem to mould the individuals to it
    #Create a random individual.
    self.chromosome =np.random.choice([True,False],prob.number_of_genes)
    self.cost = problem.cost_function(self.chromosome)

  def crossover(self,other_parent):
    # Pick a crossover point
    point = np.random.randint(1, len(self.chromosome) - 1)
    child1 = self.chromosome[:point] + other_parent.chromosome[point:]
    child2 = other_parent.chromosome[:point] + self.chromosome[point:]
    return child1, child2

  def mutate(self,mutation_rate):
    for i in range(len(self.chromosome)):
      if(np.random.uniform() < mutation_rate):
        self.chromosome[i] = not self.chromosome[i]


# Search Tree Algorithm
## Tutorial

In [50]:
class Current_Board():
  board = ""

  def __init__(self, string_def = " "*9):
    """
      Initializing a string with length 9 that represents a tic-tac-toe board
    """
    self.board = string_def
    self.state = self.state_of_board()

  def display(self):
    c = self.board
    print(c[0] + "|" + c[1] + "|" + c[2])
    print("-----")
    print(c[3] + "|" + c[4] + "|" + c[5])
    print("-----")
    print(c[6] + "|" + c[7] + "|" + c[8])

  def all_possible_moves(self, for_piece):
    possible_moves = []
    for i in range(9):
      if self.board[i] == " ":
        possible_moves.append(Current_Board(self.board[:i] + for_piece + self.board[i+1:]))
    return possible_moves

  def other(self, piece):
    return "0" if piece == "X" else "X"

  def Eq3(self, a, b, c):
    return self.board[a] == self.board[b] and self.board[b] == self.board[c] and self.board[a] == self.board[c]

  def state_of_board(self):
    # return "U" if unfinished
    if self.Eq3(0,1,2) or self.Eq3(0,4,8) or self.Eq3(0,3,6):
      return self.board[0]
    if self.Eq3(3,4,5) or self.Eq3(1,4,7) or self.Eq3(2,4,6):
      return self.board[4]
    if self.Eq3(6,7,8) or self.Eq3(2,5,8)
      return self.board[8]
    if " " in self.board:
      return "U"
    return "D"




In [35]:
class SearchTreeNode:

  def __init__(self, board_instance, playing_as):
    self.children = []
    self.current_board = board_instance
    self.move_for = playing_as
    if self.current_board.state_of_board == "U":
      self.generate_children()
    else
      # utility function
      if self.current_board.state_of_board() == "D":
        self.value = 0
        #apply depth to be implemented next day, current is a cheat version
      if self.current_board.state_of_board() == "X":
        self.value = 1
      if self.current_board.state_of_board() == "O":
        self.value = -1

  def generate_children(self):
    for board_for_next_move in self.current_board.all_possible_moves(self.move_for):
      self.children.append(SearchTreeNode(board_for_next_move, self.current_board.other(self.move_for)))

In [45]:
board = Current_Board()
board.display()
moves = board.all_possible_moves("X")

 | | 
-----
 | | 
-----
 | | 


In [26]:
moves[0].display()

X| | 
-----
 | | 
-----
 | | 


In [27]:
moves[4].display()

 | | 
-----
 |X| 
-----
 | | 


In [39]:
st = SearchTreeNode(board, "X")

In [43]:
st.children[5].current_board.display()

 | | 
-----
 | |X
-----
 | | 


In [44]:
st.children[5].children[1].current_board.display()

 |0| 
-----
 | |X
-----
 | | 


In [51]:
test_board = Current_Board("XXXOXOXOX")
test_board.display()

X|X|X
-----
O|X|O
-----
X|O|X


In [53]:
test_board.Eq3(0, 1, 2)

True

# New Section